---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: wazuh

secretGenerator:
- name: indexer-certs
  files:
  - _certs/indexer_cluster/root-ca.pem
  - _certs/indexer_cluster/node.pem
  - _certs/indexer_cluster/node-key.pem
  - _certs/indexer_cluster/dashboard.pem
  - _certs/indexer_cluster/dashboard-key.pem
  - _certs/indexer_cluster/admin.pem
  - _certs/indexer_cluster/admin-key.pem
  - _certs/indexer_cluster/filebeat.pem
  - _certs/indexer_cluster/filebeat-key.pem
- name: dashboard-certs
  files:
  - _certs/dashboard_http/cert.pem
  - _certs/dashboard_http/key.pem
  - _certs/indexer_cluster/root-ca.pem

configMapGenerator:
- name: indexer-conf
  files:
  - indexer-stack/wazuh-indexer/indexer-conf/opensearch.yml
  - indexer-stack/wazuh-indexer/indexer-conf/internal-users.yml
- name: wazuh-conf
  files:
  - wazuh-managers/wazuh-conf/master.conf
  - wazuh-managers/wazuh-conf/worker.conf
- name: dashboard-conf
  files:
  - indexer-stack/dashboard/dashboard-conf/opensearch-dashboards.yml

resources:
- base/storage-class.yaml

- secrets/wazuh-api-cred-secret.yaml
- secrets/wazuh-authd-pass-secret.yaml
- secrets/wazuh-cluster-key-secret.yaml
- secrets/dashboard-cred-secret.yaml
- secrets/indexer-cred-secret.yaml

- wazuh-managers

- indexer-stack/wazuh-indexer/service.yaml
- indexer-stack/wazuh-indexer/cluster/service.yaml
- indexer-stack/wazuh-indexer/cluster/statefulset.yaml

- indexer-stack/dashboard/service.yaml
- indexer-stack/dashboard/deployment.yaml

images:
- name: wazuh/wazuh-dashboard
  newName: zenjoy/wazuh-dashboard
  newTag: '4.12.0'
- name: wazuh/wazuh-indexer
  newName: zenjoy/wazuh-indexer
  newTag: '4.12.0'
- name: wazuh/wazuh-manager
  newName: zenjoy/wazuh-manager
  newTag: '4.12.0'
